/** Common US used-vehicle nameplates and dealer exterior colors. */
export const VEHICLE_MODELS: Record<string, string[]> = {
  Acura: ["ILX", "Integra", "MDX", "RDX", "TLX", "TSX"],
  "Alfa Romeo": ["Giulia", "Stelvio"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8"],
  BMW: ["3 Series", "4 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7"],
  Buick: ["Enclave", "Encore", "Envision", "LaCrosse", "Regal"],
  Cadillac: ["CT5", "CTS", "Escalade", "SRX", "XT4", "XT5", "XT6"],
  Chevrolet: [
    "Blazer",
    "Bolt EV",
    "Camaro",
    "Colorado",
    "Cruze",
    "Equinox",
    "Express",
    "Impala",
    "Malibu",
    "Silverado 1500",
    "Silverado 2500",
    "Suburban",
    "Tahoe",
    "Traverse",
    "Trax",
  ],
  Chrysler: ["300", "Pacifica", "Town & Country", "Voyager"],
  Dodge: ["Challenger", "Charger", "Durango", "Grand Caravan", "Hornet", "Journey"],
  Ford: [
    "Bronco",
    "Bronco Sport",
    "EcoSport",
    "Edge",
    "Escape",
    "Expedition",
    "Explorer",
    "F-150",
    "F-250",
    "Focus",
    "Fusion",
    "Maverick",
    "Mustang",
    "Ranger",
    "Transit",
  ],
  Genesis: ["G70", "G80", "GV70", "GV80"],
  GMC: ["Acadia", "Canyon", "Sierra 1500", "Sierra 2500", "Terrain", "Yukon"],
  Honda: ["Accord", "Civic", "CR-V", "Fit", "HR-V", "Insight", "Odyssey", "Passport", "Pilot", "Ridgeline"],
  Hyundai: ["Accent", "Elantra", "Ioniq", "Ioniq 5", "Kona", "Palisade", "Santa Fe", "Sonata", "Tucson", "Venue"],
  Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80"],
  Jaguar: ["E-PACE", "F-PACE", "XE", "XF"],
  Jeep: ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Grand Wagoneer", "Renegade", "Wagoneer", "Wrangler"],
  Kia: ["Carnival", "Forte", "K5", "Niro", "Optima", "Rio", "Seltos", "Sorento", "Soul", "Sportage", "Stinger", "Telluride"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport"],
  Lexus: ["ES", "GX", "IS", "LS", "LX", "NX", "RX", "UX"],
  Lincoln: ["Aviator", "Corsair", "MKC", "MKZ", "Nautilus", "Navigator"],
  Mazda: ["CX-30", "CX-5", "CX-50", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
  "Mercedes-Benz": ["A-Class", "C-Class", "CLA", "E-Class", "GLC", "GLE", "GLS", "S-Class", "Sprinter"],
  Mini: ["Clubman", "Cooper", "Countryman"],
  Mitsubishi: ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
  Nissan: ["Altima", "Armada", "Frontier", "Kicks", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Titan", "Versa"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Rivian: ["R1S", "R1T"],
  Subaru: ["Ascent", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "WRX"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  Toyota: [
    "4Runner",
    "Avalon",
    "C-HR",
    "Camry",
    "Corolla",
    "GR86",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Supra",
    "Tacoma",
    "Tundra",
    "Venza",
  ],
  Volkswagen: ["Atlas", "Beetle", "Golf", "ID.4", "Jetta", "Passat", "Taos", "Tiguan"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90"],
};

export const VEHICLE_MAKES = Object.keys(VEHICLE_MODELS);

export const VEHICLE_COLORS = [
  "Black",
  "White",
  "Silver",
  "Gray",
  "Charcoal",
  "Blue",
  "Navy",
  "Red",
  "Burgundy",
  "Maroon",
  "Green",
  "Brown",
  "Beige",
  "Tan",
  "Gold",
  "Orange",
  "Yellow",
  "Purple",
  "Other",
];

const MODEL_YEAR_START = 1990;
const MODEL_YEAR_END = 2027;

export const VEHICLE_YEARS = Array.from(
  { length: MODEL_YEAR_END - MODEL_YEAR_START + 1 },
  (_, index) => String(MODEL_YEAR_END - index),
);

export function modelsForMake(make: string) {
  return VEHICLE_MODELS[make] ?? [];
}
